# Generated by Django 6.0.3 on 2026-03-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('forecasting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(default='BC-000000000', max_length=128)),
                ('status', models.CharField(default='En attente', max_length=32)),
                ('montant_total', models.FloatField(default=0)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('livraison_prevue', models.DateTimeField(blank=True, null=True)),
                ('livraison_actuelle', models.DateTimeField(blank=True, null=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.supplier')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-creer_le'],
            },
        ),
        migrations.CreateModel(
            name='ContenuDans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product')),
                ('recommandation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.recommandation')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='DonneeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendu', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_applique', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('canal_vente', models.CharField(blank=True, default='', max_length=128)),
                ('segment_clientele', models.CharField(blank=True, default='', max_length=128)),
                ('donne_supplementaire', models.FileField(blank=True, null=True, upload_to='donnee_vente/')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donnee_ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donnée de vente',
                'verbose_name_plural': 'Données de vente',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='ProduitRenvoie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retourner', models.IntegerField(default=0)),
                ('raison_retour', models.CharField(default='', max_length=128)),
                ('condition_retour', models.CharField(default='', max_length=32)),
                ('montant_remise', models.FloatField(blank=True, null=True)),
                ('est_reapprovisionnnable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Produit renvoyé',
                'verbose_name_plural': 'Produits renvoyés',
                'ordering': ['-date_retour'],
            },
        ),
        migrations.CreateModel(
            name='ProduitDonneeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commandes.donneevente')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Produit — donnée de vente',
                'verbose_name_plural': 'Produits — données de vente',
                'unique_together': {('produit', 'donnee_vente')},
            },
        ),
    ]
