# Generated by Django 6.0.3 on 2026-05-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_remove_product_theorical_capacity_and_more'),
        ('commandes', '0002_alter_donneevente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenudans',
            name='produit_dv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.produitdv'),
        ),
        migrations.AddField(
            model_name='produitdonneevente',
            name='produit_dv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.produitdv'),
        ),
    ]
