# Generated by Django 6.0.3 on 2026-05-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_remove_product_theorical_capacity_and_more'),
        ('commandes', '0003_contenudans_produit_dv_produitdonneevente_produit_dv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produitdonneevente',
            unique_together={('produit', 'produit_dv', 'donnee_vente')},
        ),
    ]
