# Generated by Django 6.0.3 on 2026-05-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_produitdonneevente_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenudans',
            name='recommandation',
        ),
    ]
