# Generated by Django 6.0.3 on 2026-05-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_remove_contenudans_recommandation'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='montant_paye',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='statut_paiement',
            field=models.CharField(choices=[('Non payé', 'Non payé'), ('Partiel', 'Partiel'), ('Payé', 'Payé')], default='Non payé', max_length=32),
        ),
        migrations.AddField(
            model_name='donneevente',
            name='mode_paiement',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Orange Money', 'Orange Money'), ('YAS', 'YAS'), ('Airtel Money', 'Airtel Money'), ('Autre', 'Autre')], default='Espèces', max_length=32),
        ),
        migrations.AddField(
            model_name='donneevente',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='donneevente',
            name='statut_paiement',
            field=models.CharField(choices=[('Non payé', 'Non payé'), ('Partiel', 'Partiel'), ('Payé', 'Payé')], default='Non payé', max_length=32),
        ),
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Orange Money', 'Orange Money'), ('YAS', 'YAS'), ('Airtel Money', 'Airtel Money'), ('Autre', 'Autre')], max_length=32)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.boncommande')),
                ('donnee_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.donneevente')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
