# Generated by Django 6.0.3 on 2026-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_boncommande_montant_paye_boncommande_statut_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneevente',
            name='statut_paiement',
            field=models.CharField(choices=[('Non payé', 'Non payé'), ('Partiel', 'Partiel'), ('Payé', 'Payé'), ('Annulé', 'Annulé')], default='Non payé', max_length=32),
        ),
    ]
