# Generated by Django 6.0.3 on 2026-05-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_remove_product_theorical_capacity_and_more'),
        ('commandes', '0007_alter_donneevente_statut_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneevente',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Annulé', 'Annulé')], default='En attente', max_length=32),
        ),
        migrations.AddField(
            model_name='donneevente',
            name='type_vente',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Crédit', 'Crédit')], default='Normal', max_length=32),
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('Achat', 'Achat'), ('Vente', 'Vente'), ('Retour', 'Retour')], default='Retour', max_length=20)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('numero_transaction', models.CharField(blank=True, default='', max_length=128)),
                ('quantite', models.IntegerField(default=0)),
                ('montant', models.FloatField(default=0)),
                ('raison', models.CharField(default='', max_length=255)),
                ('date_remboursement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date_remboursement'],
            },
        ),
        migrations.DeleteModel(
            name='ProduitRenvoie',
        ),
    ]
