# Generated by Django 6.0.3 on 2026-05-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_donneevente_status_donneevente_type_vente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneevente',
            name='canal_vente',
        ),
        migrations.AddField(
            model_name='boncommande',
            name='mode_paiement',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Virement', 'Virement'), ('Chèque', 'Chèque'), ('Orange Money', 'Orange Money'), ('YAS', 'YAS'), ('Airtel Money', 'Airtel Money'), ('Autre', 'Autre')], default='Espèces', max_length=32),
        ),
        migrations.AddField(
            model_name='donneevente',
            name='delai_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='statut_reglement',
            field=models.CharField(choices=[('Réglé', 'Réglé'), ('Non réglé', 'Non réglé')], default='Non réglé', max_length=32),
        ),
        migrations.AddField(
            model_name='transactionpaiement',
            name='remboursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.remboursement'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='date_commande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
