# Generated by Django 6.0.3 on 2026-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_remove_donneevente_canal_vente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contenudans',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contenudans',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donneevente',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='En attente', max_length=32),
        ),
        migrations.AlterField(
            model_name='produitdonneevente',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
