# Generated by Django 6.0.3 on 2026-03-27 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='Inventaire du mois', max_length=255)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'inventaire",
                'verbose_name_plural': "Historiques d'inventaire",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSeuilStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_seuil', models.IntegerField(blank=True, default=0, null=True)),
                ('nouveau_seuil', models.IntegerField(blank=True, default=0, null=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('changer_le', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.product')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique seuil stock',
                'verbose_name_plural': 'Historiques seuil stock',
                'ordering': ['-changer_le'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theo', models.IntegerField(default=0)),
                ('quantite_phy', models.IntegerField(default=0)),
                ('ecart', models.IntegerField(default=0)),
                ('historique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.historiqueinventaire')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.produitdv')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement'), ('RETURN', 'Retour Client'), ('SCRAP', 'Rebut')], max_length=32, verbose_name='Type de mouvement')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('referrence', models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date du mouvement')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='catalogue.product', verbose_name='Produit')),
                ('produit_dv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.produitdv', verbose_name='Variante produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur responsable')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'MOVEMENT_STOCK',
                'ordering': ['-timestamp'],
            },
        ),
    ]
