# Generated by Django 6.0.3 on 2026-05-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_mouvementstock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement'), ('RETURN', 'Retour Client'), ('SCRAP', 'Rebut'), ('ALLOCATION', 'Allocation')], max_length=32, verbose_name='Type de mouvement'),
        ),
    ]
