# Generated by Django 6.0.3 on 2026-05-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_mouvementstock_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='count_override',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'unités (Saisie manuelle)"),
        ),
    ]
