# Generated by Django 6.0.3 on 2026-05-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_mouvementstock_count_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='count_override',
        ),
    ]
