# Generated by Django 6.0.3 on 2026-05-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_mouvementstock_count_override'),
    ]

    operations = [
    ]
