# Generated by Django 6.0.3 on 2026-05-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_fill_quantite_theo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='produit_cache',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom produit (cache)'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité'),
        ),
    ]
