# Generated by Django 6.0.3 on 2026-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_inventaire_produit_cache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='ecart',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='quantite_phy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='quantite_theo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
