# Generated by Django 6.0.3 on 2026-03-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alert', models.CharField(max_length=100)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('secondaire', 'Importance secondaire')], default='secondaire', max_length=32)),
                ('message', models.TextField()),
                ('compteur', models.PositiveBigIntegerField(default=0)),
                ('donnee_alerte', models.ImageField(blank=True, null=True, upload_to='alerte/')),
                ('est_lu', models.BooleanField(default=False)),
                ('est_resolu', models.BooleanField(default=False)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('resolu_le', models.DateTimeField(blank=True, null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-creer_le'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Notification', max_length=200)),
                ('message', models.TextField()),
                ('priorite', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('non lu', 'Non lu'), ('lu', 'Lu')], default='non lu', max_length=50)),
                ('channel', models.CharField(choices=[('Interne', 'Interne'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='Interne', max_length=50)),
                ('type_notification', models.CharField(default='général', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-creer_le'],
            },
        ),
    ]
