# Generated by Django 6.0.3 on 2026-04-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activite',
        ),
    ]
