# Generated by Django 6.0.3 on 2026-05-12 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Terminé', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Généré',
                'verbose_name_plural': 'Rapports Générés',
                'ordering': ['-created_at'],
            },
        ),
    ]
