# Generated by Django 6.0.3 on 2026-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='generated_reports/'),
        ),
    ]
