# Generated by Django 6.0.3 on 2026-03-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file_uploaded', models.FileField(upload_to='data_imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.FloatField(blank=True, null=True)),
                ('update_table', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SYNC', 'En cours'), ('FAILED', 'Échoué'), ('DONE', 'Terminé')], default='PENDING', max_length=32)),
                ('target_table', models.CharField(choices=[('produit', 'Produit'), ('generer', 'Mouvement stock'), ('categorie', 'Catégorie'), ('supplier', 'Fournisseur')], default='produit', max_length=50)),
            ],
            options={
                'verbose_name': 'Import de données',
                'verbose_name_plural': 'Imports de données',
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id_modele', models.AutoField(primary_key=True, serialize=False)),
                ('nom_modele', models.CharField(max_length=128)),
                ('parametre_model', models.TextField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, default=0)),
                ('rmse', models.FloatField(blank=True, default=0)),
                ('mape', models.FloatField(blank=True, default=0)),
                ('score', models.FloatField(blank=True, default=0)),
                ('periode_evaluation', models.SmallIntegerField(default=7)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('journal_execution', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('ERR', 'Erreur')], default='PENDING', max_length=32)),
                ('enregistrement_traite', models.IntegerField(default=0)),
                ('enregistrement_reussi', models.IntegerField(default=0)),
                ('enregistrement_echoue', models.IntegerField(default=0)),
                ('commence_le', models.DateTimeField(auto_now_add=True)),
                ('complete_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_pipelines', to='forecasting.dataimport')),
            ],
            options={
                'verbose_name': "Pipeline d'exécution",
                'verbose_name_plural': "Pipelines d'exécution",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prediction', models.DateField()),
                ('import_qty', models.FloatField(default=0)),
                ('import_lower_bound', models.FloatField(blank=True, null=True)),
                ('import_upper_bound', models.FloatField(blank=True, null=True)),
                ('export_qty', models.FloatField(default=0)),
                ('export_lower_bound', models.FloatField(blank=True, null=True)),
                ('export_upper_bound', models.FloatField(blank=True, null=True)),
                ('stock_prevu', models.FloatField(default=0)),
                ('rupture', models.BooleanField(default=False)),
                ('horizon', models.IntegerField()),
                ('modele_utilise', models.CharField(max_length=100)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
                'ordering': ['-date_prediction'],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prediction', models.DateField(blank=True, null=True)),
                ('type_recommandation', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('quantite_suggeree', models.IntegerField(blank=True, default=0, null=True)),
                ('prix_estime', models.FloatField(blank=True, default=0.0, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='MOYENNE', max_length=32, null=True)),
                ('raisonnement', models.TextField(blank=True, default='', null=True)),
                ('donnee_appui', models.FileField(blank=True, null=True, upload_to='recommandation/donnee_appui/')),
                ('est_applique', models.BooleanField(blank=True, default=False, null=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True, null=True)),
                ('appliquee_le', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='catalogue.product')),
                ('utilisateurs_appliquants', models.ManyToManyField(blank=True, related_name='recommandations_appliquees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'constraints': [models.UniqueConstraint(fields=('product', 'date_prediction'), name='unique_recommandation_per_product_date')],
            },
        ),
        migrations.CreateModel(
            name='RuptureStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rupture', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Rupture de stock',
                'unique_together': {('date', 'product')},
            },
        ),
    ]
