# Generated by Django 6.0.3 on 2026-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_supplier_created_at_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='catalogue.product'),
        ),
    ]
