# Generated by Django 6.0.3 on 2026-05-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_supplier_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='theorical_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='theorical_unit',
            field=models.CharField(blank=True, default='pièces', max_length=50, null=True),
        ),
    ]
