# Generated by Django 6.0.3 on 2026-05-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_theorical_capacity_product_theorical_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitdv',
            name='nombre',
            field=models.IntegerField(blank=True, default=0, verbose_name="Nombre d'unités"),
        ),
        migrations.AlterField(
            model_name='produitdv',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Capacité (Unités/Kg)'),
        ),
    ]
