# Generated by Django 6.0.3 on 2026-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_product_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='theorical_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='theorical_unit',
        ),
        migrations.RemoveField(
            model_name='produitdv',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='produitdv',
            name='nombre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Stock'),
        ),
    ]
